---
- hosts: appserver
  tasks:
    - name: Register a var
      set_fact:
        ALL_ENV:
          - DEV
          - QA
          - PROD
    - name: test var
      debug:
        msg: "state: {{ item.0 }}; path: {{ item.1 }}"
      with_nested: 
      - [ SURESH,'RAMESH {{ item.1 }}' ]
      - [4,5,6]



    
