---
- hosts: appserver
  tasks:
    - name: Register a var
      set_fact:
        ALL_ENV:
          - DEV
          - QA
          - PROD
    - name: test var
      debug:
        msg: "{{ item }}"
      with_items: '{{ ALL_ENV }}'



    
