---
# vars file for localhost
git_checkout_path: 'D:\Projects\GAMODS DEV\Workspace\onaraya\AlphaGAMODS75053'
temp_dir: 'D:\ansible_temp'
temp_artifacts: '{{ temp_dir }}\artifacts'
artifact_copy:
- {path: '{{ git_checkout_path}}\ODS_python', dest: '{{ temp_artifacts }}\{{ windows_artifact_commit }}' }
- {path: '{{ git_checkout_path}}\ODS_batch', dest: '{{ temp_artifacts }}\{{ windows_artifact_commit }}' }
- {path: '{{ git_checkout_path}}\ODS_datastore', dest: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}' }
- {path: '{{ git_checkout_path}}\ODS_build', dest: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}' }
