---
# vars file for localhost
git_checkout_path: 'D:\Projects\GAMODS DEV\Workspace\onaraya\AlphaGAMODS75053'
temp_dir: 'D:\ansible_temp'
temp_artifacts: '{{ temp_dir }}\artifacts'
artifact_copy:
- {path: '{{ git_checkout_path}}\ODS_python', dest: '{{ temp_artifacts }}\{{ windows_artifact_commit }}' }
- {path: '{{ git_checkout_path}}\ODS_batch', dest: '{{ temp_artifacts }}\{{ windows_artifact_commit }}' }
- {path: '{{ git_checkout_path}}\ODS_datastore', dest: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}' }
- {path: '{{ git_checkout_path}}\ODS_build', dest: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}' }
token_replace_script_path: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}\ODS_build\replace_token.ps1'
snowflake_config_file_path: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}\ODS_build\Config.CSV'
ODS_Batch_path: '{{ temp_artifacts }}\{{ windows_artifact_commit }}\ODS_Batch'
ODS_datastore_path: '{{ temp_artifacts }}\{{ windows_artifact_commit }}\ODS_Datastore'
deployment_environment_array: 
- 'DEV2'
- 'QA'
- 'UAT'
- 'Prod'