---
all:
  children:
    appserver:
      hosts:  
        # 40.71.19.153:
        ansible-node1.eastus.cloudapp.azure.com:
  vars:
    ansible_connection: winrm
    ansible_user: sroot
    ansible_password: linux@123qwe
    artifact_version: 1.1
    ansible_winrm_transport: basic
    ansible_port: 5985
    ansible_winrm_server_cert_validation: ignore
    windows_artifacts: "windows_artifacts"
    snowflake_artifacts: "snowflake_artifacts"

    # ansible_winrm_transport: kerberos
