# all:
#   children:
#     local:
#       children:
#         hosts:
#           localhost:
#     appserver:
#       children:
#         hosts:
#           ansible-node1.eastus.cloudapp.azure.com:
# vars:
#   artifact_version: 1.1