---
- name: Executing '{{ token_replace_script_path }}' for {{ env_name }} environment's snowlfake floder.
    & {{ token_replace_script_path }} -configFile {{ snowflake_config_file_path }} -replaceDirectory {{ ODS_datastore_path }}\*.sql -env '{{ env_name }}'
  register: snowflake_token_replace_output

- name: Executing '{{ token_replace_script_path }} for {{ env_name }} environment's windows floder'
  win_shell: |
    & {{ token_replace_script_path }} -configFile {{ snowflake_config_file_path }} -replaceDirectory {{ ODS_Batch_path }}\*.bat -env '{{ env_name }}'
  register: windows_token_replace_output

- name: perform Zip operation to compress artifact of {{ env_name }}environment.
  win_shell: |
    Compress-Archive -Path "{{ aritafact_path.path }}/*" -DestinationPath "{{ aritafact_path.dest }}" -update -verbose
  with_items: 
  - { path: '{{ temp_artifacts }}\{{ windows_artifact_commit }}' , dest: '{{ temp_artifacts }}\{{ windows_artifact_commit }}-{{ env_name }}.zip' }
  - { path: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}', dest: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}-{{ env_name }}.zip' }
  loop_control:
    loop_var: aritafact_path

- name: Copying {{ env_name }} environment's artifacts to github repo
  win_copy:
      src: "{{ artifactory_copy_zip.src }}"
      dest: "{{ artifactory_copy_zip.dest }}"
      remote_src: yes
  with_items:
    - { src: '{{ temp_artifacts }}\{{ windows_artifact_commit }}-{{ env_name }}.zip', dest: '{{ temp_artifacts }}\artifact_server\artifactory\windows_artifacts\{{ windows_artifact_commit }}-{{ env_name }}.zip' }
    - { src: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}-{{ env_name }}.zip', dest: '{{ temp_artifacts }}\artifact_server\artifactory\snowflake_artifacts\{{ snowflake_artifact_commit }}-{{ env_name }}.zip' }
  loop_control:
    loop_var: artifactory_copy_zip
