--- 
- name: Creates directories if not available
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
  - '{{ temp_artifacts }}\artifact_server'

- name: Copy bat file
  win_copy:
    src: "sparse-checkout.bat"
    dest: '{{ temp_artifacts }}\artifact_server\'
    force: yes

- name: Clone artifact repository from github
  win_shell: |
    Start-Process -FilePath "{{ temp_artifacts }}\artifact_server\sparse-checkout.bat" -Wait -NoNewWindow -Args "{{ temp_artifacts }}\artifact_server","https://github.com/Sureshsingh7/ansible-scripts.git","artifactory","master"

# - name: Creates directories if not available
#   file:
#     path: "{{ item }}"
#     state: directory
#   with_items:
#   - 'roles/localhost/files/artifact_server/{{ windows_artifacts }}'
#   - 'roles/localhost/files/artifact_server/{{ snowflake_artifacts }}'

- name: Copying artifacts to github repo
  win_copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: yes
  with_items:
    - { src: '{{ temp_artifacts }}\{{ windows_artifact_commit }}.zip', dest: '{{ temp_artifacts }}\artifact_server\artifactory\windows_artifacts\{{ windows_artifact_commit }}.zip' }
    - { src: '{{ temp_artifacts }}\{{ snowflake_artifact_commit }}.zip', dest: '{{ temp_artifacts }}\artifact_server\artifactory\snowflake_artifacts\{{ snowflake_artifact_commit }}.zip' }

- name: commit artifacts to github
  win_shell: |
    cd '{{ temp_artifacts }}\artifact_server\artifactory'
    git add .
    git commit -m "artifacts added to git repo"
    git push https://Sureshsingh7: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@github.com/Sureshsingh7/ansible-scripts.git --all
