--- 
- name: Clone artifact repository from github
  git:
    repo: https://Sureshsingh7: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@github.com/Sureshsingh7/artifact_repo.git
    dest: roles/localhost/files/artifact_server/
    clone: yes
    update: yes

- name: Creates directories if not available
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - 'roles/localhost/files/artifact_server/{{ windows_artifacts }}'
  - 'roles/localhost/files/artifact_server/{{ snowflake_artifacts }}'

- name: Copying artifacts to github repo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'roles/localhost/files/artifacts/{{ python_artifacts }}-{{ artifact_version }}.zip', dest: 'roles/localhost/files/artifact_server/ODS_build/{{ windows_artifacts }}-{{ artifact_version }}.zip' }
    - { src: 'roles/localhost/files/artifacts/{{ snowflake_artifacts }}-{{ artifact_version }}.zip', dest: 'roles/localhost/files/artifact_server/ODS_datastore/{{ snowflake_artifacts }}-{{ artifact_version }}.zip' }

- name: commit artifacts to github
  shell: |
    cd roles/localhost/files/artifact_server/
    git add .
    git commit -m "artifacts added to git repo"
    git push https://Sureshsingh7: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@github.com/Sureshsingh7/ansible-scripts.git --all
