--- 
- name: Creates directories if not available
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
  - 'D:/ansible_temp/artifacts/artifact_server'

- name: Clone artifact repository from github
  win_shell: |
    cd D:/ansible_temp/artifacts/artifact_server
    git init
    git config core.sparsecheckout true
    echo artifactory >> .git/info/sparse-checkout
    git remote add -f origin https://Sureshsingh7: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@github.com/Sureshsingh7/ansible-scripts.git
    git pull origin master

# - name: Creates directories if not available
#   file:
#     path: "{{ item }}"
#     state: directory
#   with_items:
#   - 'roles/localhost/files/artifact_server/{{ windows_artifacts }}'
#   - 'roles/localhost/files/artifact_server/{{ snowflake_artifacts }}'

- name: Copying artifacts to github repo
  win_copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: yes
  with_items:
    - { src: 'D:\ansible_temp\artifacts\{{ windows_artifacts }}-{{ artifact_version }}.zip', dest: 'D:\ansible_temp\artifacts\artifact_server\artifactory\windows_artifacts\{{ windows_artifacts }}-{{ artifact_version }}.zip' }
    - { src: 'D:\ansible_temp\artifacts\{{ snowflake_artifacts }}-{{ artifact_version }}.zip', dest: 'D:\ansible_temp\artifacts\artifact_server\artifactory\snowflake_artifacts\{{ snowflake_artifacts }}-{{ artifact_version }}.zip' }

- name: commit artifacts to github
  win_shell: |
    cd 'D:\ansible_temp\artifacts\artifact_server\artifactory'
    git add .
    git commit -m "artifacts added to git repo"
    git push https://Sureshsingh7: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@github.com/Sureshsingh7/ansible-scripts.git --all
