--- 
- name: Check connectivity for all the servers
  win_ping:

- name: Create artifact folder
  win_file:
    path: '{{ git_checkout_path }}'
    state: absent

- name: Create artifact folder
  win_file:
    path: '{{ git_checkout_path }}'
    state: directory

- name: Clone project directory
  win_shell: |
    git clone https://{{ project_repo_url }} --branch {{ project_branch }} '{{ git_checkout_path }}'
    
- name: Create artifact folder
  win_file:
    path: '{{ temp_artifacts }}'
    state: directory
    
- name: combining deployable artifacts
  win_copy:
      src: "{{ item.path }}"     
      dest: "{{ item.dest }}"
      remote_src: yes
  loop: '{{ artifact_copy }}'   

- name: set environment name  for {{ env_type }} environment
  set_fact:
    environment_name: "{{ env_type }}"
  when: env_type!='ALL'

- name: set environment name array environment
  set_fact:
    environment_name: "{{ deployment_environment_array }}"
  when: env_type=='ALL'

- name: Creates directories if not available for artifactory checkout
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
  - '{{ temp_artifacts }}\artifact_server'

- name: Copy bat file for sparse checkout
  win_copy:
    src: "sparse-checkout.bat"
    dest: '{{ temp_artifacts }}\artifact_server\'
    force: yes

- name: Clone artifact repository from github
  win_shell: |
    Start-Process -FilePath "{{ temp_artifacts }}\artifact_server\sparse-checkout.bat" -Wait -NoNewWindow -Args "https://Sureshsingh7:{{ github_token }}@{{ artifact_repo_url }}","artifactory","master"
  args:
    chdir: '{{ temp_artifacts }}\artifact_server'

- name: Execute token replacement scripts for windows and snowflakes
  include_tasks: build_artifact.yml
  with_items: '{{ environment_name }}'
  loop_control:
    loop_var: env_name

- name: commit artifacts to github
  win_shell: |
    cd '{{ temp_artifacts }}\artifact_server\artifactory'
    git add .
    git commit -m "artifacts added to git repo"
    git push https://Sureshsingh7:{{ github_token }}@{{ artifact_repo_url }} --all


# # - name: Including task for commiting artifact to github repo
# #   include_tasks: commit_artifact.yml

# - name: Remove ansible_temp folder
#   win_file:
#     path: '{{ temp_dir }}'
#     state: absent
#     force: yes
