--- 
- name: Check connectivity for all the servers
  win_ping:

# - name: Clone project directory
#   win_git:
#     repo: "https://github.com/Sureshsingh7/Test.git"
#     dest: "D:\\Project\\GAMODS DEV\\Workspace\\onaraya\\AlphaGAMODS75053"
#     clone: yes
#     update: yes
#     branch: master

- name: Create artifact folder
  win_file:
    path: '{{ temp_artifacts }}'
    state: directory
    
- name: combining deployable artifacts
  win_copy:
      src: "{{ item.path }}"     
      dest: "{{ item.dest }}"
      remote_src: yes
  loop: '{{ artifact_copy }}'
  
- name: perform Zip operation
  community.windows.win_zip:
    src: "{{ item.path }}"
    dest: "{{ item.dest }}"
  with_items: 
  - { path: '{{ temp_artifacts }}\{{ windows_artifacts }}-{{ artifact_version }}' , dest: '{{ temp_artifacts }}\{{ windows_artifacts }}-{{ artifact_version }}.zip' }
  - { path: '{{ temp_artifacts }}\{{ snowflake_artifacts }}-{{ artifact_version }}', dest: '{{ temp_artifacts }}\{{ snowflake_artifacts }}-{{ artifact_version }}.zip' }

- name: Including task for commiting artifact to github repo
  include_tasks: commit_artifact.yml

# - name: Remove ansible_temp folder
#   win_file:
#     path: '{{ temp_dir }}'
#     state: absent
#     force: yes
