--- 
- name: Check connectivity for all the servers
  win_ping:

- name: Removing old code folder.
  win_file:
    path: '{{ git_checkout_path }}'
    state: absent

- name: Creating folder to checkout Code repo.
  win_file:
    path: '{{ folder_path }}'
    state: directory
  with_items:
  - '{{ temp_artifacts }}\artifact_server'
  - '{{ git_checkout_path }}'
  loop_control:
    loop_var: folder_path

- name: Clone Code repo from github
  win_shell: |
    git clone https://{{ project_repo_url }} --branch {{ project_branch }} '{{ git_checkout_path }}'
    
- name: Create temporary folder for performing all the operations on host machine.
  win_file:
    path: '{{ temp_artifacts }}'
    state: directory
    
- name: Getting artifacts to create folder for {{ windows_artifacts }} and {{ snowflake_artifacts }}
  win_copy:
      src: "{{ item.path }}"     
      dest: "{{ item.dest }}"
      remote_src: yes
  loop: '{{ artifact_copy }}'   

- name: setting up environment name for {{ env_type }}
  set_fact:
    environment_name: "{{ env_type }}"
  when: env_type!='ALL'

- name: setting up environment name array for creating artifacts for multiple environments.
  set_fact:
    environment_name: "{{ deployment_environment_array }}"
  when: env_type=='ALL'

- name: Copying bat file for sparse checkout.
  win_copy:
    src: "sparse-checkout.bat"
    dest: '{{ temp_artifacts }}\artifact_server\'
    force: yes

- name: Clone artifact repository from github with sparse checkout.
  win_shell: |
    Start-Process -FilePath "{{ temp_artifacts }}\artifact_server\sparse-checkout.bat" -Wait -NoNewWindow -Args "https://Sureshsingh7:{{ github_token }}@{{ artifact_repo_url }}","artifactory","master"
  args:
    chdir: '{{ temp_artifacts }}\artifact_server'

- name: Execute token replacement scripts for windows and snowflakes
  include_tasks: build_artifact.yml
  with_items: '{{ environment_name }}'
  loop_control:
    loop_var: env_name

- name: commit artifacts to github
  win_shell: |
    cd '{{ temp_artifacts }}\artifact_server\artifactory'
    git add .
    git commit -m "artifacts added to git repo"
    git push https://Sureshsingh7:{{ github_token }}@{{ artifact_repo_url }} --all

- name: Remove ansible_temp folder
  win_file:
    path: '{{ temp_dir }}'
    state: absent
    force: yes
