--- 
- name: Check connectivity for all the servers
  win_ping:

- name: Create artifact folder
  win_file:
    path: '{{ git_checkout_path }}'
    state: absent

- name: Create artifact folder
  win_file:
    path: '{{ git_checkout_path }}'
    state: directory

- name: Clone project directory
  win_shell: |
    git clone https://{{ project_repo_url }} --branch {{ project_branch }} '{{ git_checkout_path }}'
    
- name: Create artifact folder
  win_file:
    path: '{{ temp_artifacts }}'
    state: directory
    
- name: combining deployable artifacts
  win_copy:
      src: "{{ item.path }}"     
      dest: "{{ item.dest }}"
      remote_src: yes
  loop: '{{ artifact_copy }}'   

- name: set environment name  for {{ env_type }} environment
  set_fact:
    environment_name: "{{ env_type }}"
  when: env_type!='ALL'

- name: set environment name array environment
  set_fact:
    environment_name: "{{ deployment_environment_array }}"
  when: env_type=='ALL'

- name: Execute token replacement scripts for windows and snowflakes
  include_tasks: build_artifact.yml
  with_items: '{{ environment_name }}'
  loop_control:
    loop_var: env_name


# # - name: Including task for commiting artifact to github repo
# #   include_tasks: commit_artifact.yml

# - name: Remove ansible_temp folder
#   win_file:
#     path: '{{ temp_dir }}'
#     state: absent
#     force: yes
