--- 
- name: Check connectivity for all the servers
  win_ping:

- name: Create artifact folder
  win_file:
    path: '{{ git_checkout_path }}'
    state: directory

- name: Clone project directory
  win_shell: |
    git clone https://github.com/Sureshsingh7/Test.git --branch master {{ git_checkout_path }}
    
- name: Create artifact folder
  win_file:
    path: '{{ temp_artifacts }}'
    state: directory
    
- name: combining deployable artifacts
  win_copy:
      src: "{{ item.path }}"     
      dest: "{{ item.dest }}"
      remote_src: yes
  loop: '{{ artifact_copy }}'
  
- name: perform Zip operation
  win_shell: |
    Compress-Archive -Path "{{ item.path }}/*" -DestinationPath "{{ item.dest }}" -update -verbose
    # src: "{{ item.path }}"
    # dest: "{{ item.dest }}"
  with_items: 
  - { path: '{{ temp_artifacts }}\{{ windows_artifacts }}-{{ artifact_version }}' , dest: '{{ temp_artifacts }}\{{ windows_artifacts }}-{{ artifact_version }}.zip' }
  - { path: '{{ temp_artifacts }}\{{ snowflake_artifacts }}-{{ artifact_version }}', dest: '{{ temp_artifacts }}\{{ snowflake_artifacts }}-{{ artifact_version }}.zip' }

- name: Including task for commiting artifact to github repo
  include_tasks: commit_artifact.yml

- name: Remove ansible_temp folder
  win_file:
    path: '{{ temp_dir }}'
    state: absent
    force: yes
