--- 
- name: Clone github repository
  git:
    repo: https://github.com/Sureshsingh7/Test.git
    dest: roles/localhost/files/github_repo/
    clone: yes
    update: 'yes'

- name: Create artifact folder
  file:
    path: roles/localhost/files/artifacts
    state: directory

- name: perform Zip operation
  archive:
    path:
    -  "{{ item.path.path1 }}"
    -  "{{ item.path.path2 }}"
    dest: "{{ item.dest }}"
    format: zip
  with_items: 
  - { path: {path1: roles/localhost/files/github_repo/ODS_python/, path2: roles/localhost/files/github_repo/ODS_batch}, dest: 'roles/localhost/files/artifacts/{{  windows_artifacts }}-{{ artifact_version }}.zip' }
  - { path: {path1: roles/localhost/files/github_repo/ODS_datastore/, path2: roles/localhost/files/github_repo/ODS_build}, dest: 'roles/localhost/files/artifacts/{{  snowflake_artifacts  }}-{{ artifact_version }}.zip' }

- name: Including task for commiting artifact to github repo
  include_tasks: commit_artifact.yml
