---
- name: Check whether script exist or not
  win_stat:
    path: '{{ token_replace_script_path}}'
  register: script_exist

- name: Fail if script is not present
  fail:
    msg: 'Execution failed due to {{ token_replace_script_path}} does not exist'
  when: not script_exist.stat.exists

- name: Executing '{{ token_replace_script_path }}'
  win_shell: |
    & {{ token_replace_script_path }} -configFile {{ snowflake_config_file_path }} -replaceDirectory {{ ODS_datastore_path }}\*.sql -env '{{ deployment_environment }}'
  register: snowflake_token_replace_output

- name: Rollback the challenges if script failed
  debug:
    msg: "{{ snowflake_token_replace_output.stderr }}"  
  when: snowflake_token_replace_output.stderr!=""

- name: Executing '{{ token_replace_script_path }} for batch scripts'
  win_shell: |
    & {{ snwoflake_token_replace_script_path }} -configFile {{ snowflake_config_file_path }} -replaceDirectory {{ ODS_Batch_path }}\*.bat -env '{{ deployment_environment }}'
  register: windows_token_replace_output

- name: Rollback the challenges if script failed
  debug:
    msg: "{{ windows_token_replace_output.stderr }}"  
  when: windows_token_replace_output.stderr!=""
