---
- name: Download artifacts and start deployment with script execution
  block:
    - name: Create folder for checkout artifactory 
      win_file: 
        path: "{{ temp_artifactory }}"
        state: directory

    - name: Copying bat file for sparse checkout of artifactory for deployment
      win_copy:
        src: "sparse-checkout.bat"
        dest: '{{ temp_artifactory }}\'
        force: yes

    - name: Clone artifact repository from github for deployment
      win_shell: |
        Start-Process -FilePath "{{ temp_artifactory }}\sparse-checkout.bat" -Wait -NoNewWindow -Args 'https://{{ scm_user }}:{{ github_token }}@{{ artifact_repo_url }}',"artifactory",'{{ artifact_repo_branch }}'
      register: stderr
      args:
        chdir: '{{ temp_artifactory }}'

    - name: Including task for preparing the {{ windows_artifacts }} in server
      include_tasks: prepare_appserver.yml

    - name:  Including task for preparing the {{ snowflake_artifacts }} in server
      include_tasks: prepare_dbserver.yml

    - name: Including task for executing the scripts
      include_tasks: execute_script.yml
  always:
    - name: delete temp directory.
      win_file:
        path: '{{ temp_artifactory }}'
        state: absent
