---
- name: Download artifacts and start deployment with script execution
  block:
    - name: Create folder for checkout artifactory 
      win_file: 
        path: "{{ temp_artifactory }}"
        state: directory

    - name: Copy bat file
      win_copy:
        src: "sparse-checkout.bat"
        dest: '{{ temp_artifactory }}\'
        force: yes

    - name: Clone artifact repository from github
      win_shell: |
        Start-Process -FilePath "{{ temp_artifactory }}\sparse-checkout.bat" -Wait -NoNewWindow -Args 'https://Sureshsingh7:{{ github_token }}@{{ artifact_repo_url }}',"artifactory","master"
      register: stderr
      args:
        chdir: '{{ temp_artifactory }}'

    - name: debug
      debug:
        msg: '{{ stderr }}'

    - name: Including task for preparing the {{ windows_artifacts }} in server
      include_tasks: prepare_appserver.yml

    - name:  Including task for preparing the {{ snowflake_artifacts }} in server
      include_tasks: prepare_dbserver.yml

  #   - name: Including task for executing the scripts
  #     include_tasks: execute_script.yml
  # always:
  #   - name: delete temp directory.
  #     win_file:
  #       path: '{{ temp_artifactory }}'
  #       state: absent
