---
- name: Create folder for checkout artifactory 
  win_file: 
    path: "{{ temp_artifactory }}"
    state: directory

- name: Copy bat file
  win_copy:
    src: "sparse-checkout.bat"
    dest: '{{ temp_artifactory }}\'
    force: yes

- name: Clone artifact repository from github
  win_shell: |
    Start-Process -FilePath "{{ temp_artifactory }}\sparse-checkout.bat" -Wait -NoNewWindow -Args "{{ temp_artifactory }}","https://{{ artifact_repo_url }}","artifactory","master"
  register: stderr

- name: debug
  debug:
    msg: '{{ stderr }}'

- name: Including task for commiting artifact to github repo
  include_tasks: prepare_appserver.yml

- name: Including task for commiting artifact to github repo
  include_tasks: prepare_dbserver.yml

- name: delete temp directory.
  win_file:
    path: {{ temp_artifactory }}
    state: absent
    force: yes