---
- name: Check state of deployment folder.
  win_stat:
    path: "{{ deployment_folder }}\\script\\ODS_python"
  register: python_folder_exist

- name: Create Archive folder if not present
  win_file: 
    path: '{{ deployment_folder }}\archive'
    state: directory


#- name: Check whether backup folder exist or not.
#  win_stat:
#    path: "{{ deployment_folder }}\\{{ instance_name }}.bkp"
  
#  register: backup_folder_exist
  

#- name: Delete backup folder if exist.
#  win_file: 
#    path: '{{ deployment_folder }}\{{ instance_name }}.bkp'
#    state: absent
#  when:
#  - backup_folder_exist.stat.exists
#  - deployment_folder_exist.stat.exists

- name: Replace old folder to backup folder
  win_shell: | 
    Compress-Archive -Path "{{ deployment_folder }}\script\*" -DestinationPath "{{ deployment_folder }}\archive\{{ instance_name }}_{{ tower_job_id }}_bkp.zip " -update -verbose 
  when: python_folder_exist.stat.exists

# - name: Create folder for instance 
#   win_file: 
#     path: '{{ deployment_folder }}\script'
#     state: directory

- name: copy python code zip to deployment folder
  win_copy:
    src: '{{ temp_artifactory }}\artifactory\{{ windows_artifacts }}\{{ windows_artifacts }}-{{ artifact_version }}.zip'
    dest: '{{ deployment_folder }}\script\{{ windows_artifacts }}-{{ artifact_version }}.zip'
    remote_src: yes

- name: Extract war at {{ deployment_folder }}
  win_unzip:
    src: '{{ deployment_folder }}\script\{{ windows_artifacts }}-{{ artifact_version }}.zip'
    dest: '{{ deployment_folder }}\script\'
    delete_archive: yes
    
# - name: run powershell scripts 
