---
- name: debug
  debug:
    msg: '{{ windows_deployment_folder }}'
- name: Check state of deployment folder for windows artifact.
  win_stat:
    path: "{{ windows_deployment_folder }}\\ODS_python"
  register: python_folder_exist

- name: Create Archive folder if not present
  win_file: 
    path: '{{ deployment_folder }}\archive'
    state: directory


#- name: Check whether backup folder exist or not.
#  win_stat:
#    path: "{{ deployment_folder }}\\{{ instance_name }}.bkp"
  
#  register: backup_folder_exist
  

#- name: Delete backup folder if exist.
#  win_file: 
#    path: '{{ deployment_folder }}\{{ instance_name }}.bkp'
#    state: absent
#  when:
#  - backup_folder_exist.stat.exists
#  - deployment_folder_exist.stat.exists

- name: Replace old folder to backup {{ windows_artifacts }} folder 
  win_shell: | 
    Compress-Archive -Path "{{ windows_deployment_folder }}\*" -DestinationPath "{{ deployment_folder }}\archive\{{ windows_artifacts }}_{{ tower_job_id }}_bkp.zip" -update -verbose 
  when: python_folder_exist.stat.exists

- name: Create folder for instance 
  win_file: 
    path: '{{ windows_deployment_folder }}'
    state: directory

- name: copy python code zip to {{ windows_artifacts }} deployment folder
  win_copy:
    src: '{{ temp_artifactory }}\artifactory\{{ windows_artifacts }}\{{ windows_artifact_commit }}.zip'
    dest: '{{ windows_deployment_folder }}\{{ windows_artifact_commit }}.zip'
    remote_src: yes

- name: Extract war at {{ deployment_folder }}
  win_unzip:
    src: '{{ windows_deployment_folder }}\{{ windows_artifact_commit }}.zip'
    dest: '{{ windows_deployment_folder }}\'
    delete_archive: yes
    
# - name: run powershell scripts 
