---
- name: Check state of deployment folder for windows artifact.
  win_stat:
    path: "{{ windows_deployment_folder }}\\ODS_python"
  register: python_folder_exist

- name: Create Archives folder if not present
  win_file: 
    path: '{{ deployment_folder }}\Archives'
    state: directory

- name: Creating {{ deployment_folder }}\archive\{{ windows_artifacts }} 
  win_file:
    path: '{{ deployment_folder }}\Archives\{{ windows_artifacts }}'
    state: directory

- name: Replace old folder to backup {{ windows_artifacts }} folder 
  win_shell: | 
    Compress-Archive -Path "{{ windows_deployment_folder }}\*" -DestinationPath "{{ deployment_folder }}\Archives\{{ windows_artifacts }}\{{ windows_artifacts }}_{{ tower_job_id }}_bkp.zip" -update -verbose 
  when: python_folder_exist.stat.exists

- name: Create folder for instance 
  win_file: 
    path: '{{ windows_deployment_folder }}'
    state: directory

- name: copy python code zip to {{ windows_artifacts }} deployment folder
  win_copy:
    src: '{{ temp_artifactory }}\artifactory\{{ windows_artifacts }}\{{ windows_artifact_commit }}-{{ env_name }}.zip'
    dest: '{{ windows_deployment_folder }}\{{ windows_artifact_commit }}-{{ env_name }}.zip'
    remote_src: yes

- name: Extract artifact zip at {{ windows_deployment_folder }}
  win_unzip:
    src: '{{ windows_deployment_folder }}\{{ windows_artifact_commit }}-{{ env_name }}.zip'
    dest: '{{ windows_deployment_folder }}\'
    delete_archive: yes
    
